### ISSUE TITLE
all wrong answers

### ISSUE THREAD

**Issue by repath** [alexa/skill-sample-nodejs-quiz-game#48]
Dear Team,
First of all, thank you for the tutorial and the detailed step to use the code as is:
the issue, I encountered is that, even I tell the correct answer, it says "that answer is wrong" but gives the same answer as correct answer. I don't know, how to modify the code.
can you please help.
with regards
Riphath Athyala

**Comment by franklin-lobb** [comment]
I was unable to repro this issue for most question type.  There's an issue if you speak the order of statehood as 'first' vs. 'one'.  The other responses seem to map fine.  Were you experiencing this with all question types, or just specific ones?  If you can tell me the question and your answer, it'll help narrow down where the issue is.

**Comment by DarrenBro** [comment]
I believe it the issue fell down to aws lambda updates to intent.slots.Answer.value but it should be intent.slots.item.value. I fixed the issue for myself and provided my branch change so all good. Thank you.

**Comment by franklin-lobb** [comment]
fair enough.  if you have further questions, please don't hesitate to ask.
